// <auto-generated />
namespace tradutor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CriarGruposEUtilizadores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriarGruposEUtilizadores));
        
        string IMigrationMetadata.Id
        {
            get { return "202507231544160_CriarGruposEUtilizadores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
